# Generated by Django 4.2.7 on 2025-08-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('product_types', models.JSONField(default=list, help_text='Which products can use this template')),
                ('template_data', models.JSONField(help_text='Canvas data, elements, etc.')),
                ('preview_image', models.ImageField(blank=True, upload_to='templates/previews/')),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='templates/thumbnails/')),
                ('width', models.IntegerField(help_text='Width in pixels or mm')),
                ('height', models.IntegerField(help_text='Height in pixels or mm')),
                ('dpi', models.IntegerField(default=300)),
                ('color_mode', models.CharField(choices=[('RGB', 'RGB'), ('CMYK', 'CMYK')], default='CMYK', max_length=4)),
                ('tags', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('product_type', models.CharField(choices=[('book', 'Book Printing'), ('box', 'Paper Box'), ('marketing', 'Marketing Material'), ('stationery', 'Stationery')], max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=500)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_structure', models.JSONField(default=dict, help_text='Complex pricing data from Excel')),
                ('size_options', models.JSONField(default=list, help_text='Available sizes')),
                ('paper_options', models.JSONField(default=list, help_text='Paper types and GSM')),
                ('print_options', models.JSONField(default=list, help_text='Print types (B&W, Color)')),
                ('binding_options', models.JSONField(default=list, help_text='Binding options for books')),
                ('finish_options', models.JSONField(default=list, help_text='Finish options')),
                ('design_tool_enabled', models.BooleanField(default=False)),
                ('design_templates', models.JSONField(default=list, help_text='Available templates')),
                ('custom_size_allowed', models.BooleanField(default=False)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('made_to_order', 'Made to Order')], default='made_to_order', max_length=20)),
                ('lead_time_days', models.IntegerField(default=3)),
                ('rush_available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('bestseller', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-bestseller', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
    ]
