# Generated by Django 5.2.6 on 2025-09-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_front_back_design_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_subcategories',
            field=models.BooleanField(default=False, help_text='Enable subcategories for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='supports_upload',
            field=models.BooleanField(default=True, help_text='Allow users to upload their own designs'),
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='subcategories/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('size_options', models.JSONField(default=list, help_text='Available sizes for this subcategory')),
                ('paper_options', models.JSONField(default=list, help_text='Paper types for this subcategory')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Subcategories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('parent_product', 'slug')},
            },
        ),
    ]
