# Generated by Django 5.2.6 on 2025-09-15 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_subcategories_product_supports_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supports_front_back', models.BooleanField(default=False, help_text='Enable front and back design options')),
                ('template_required', models.BooleanField(default=True, help_text='Require template selection')),
                ('accepted_formats', models.JSONField(default=list, help_text='Accepted file formats for uploads')),
                ('max_file_size_mb', models.PositiveIntegerField(default=50, help_text='Maximum file size in MB')),
                ('min_resolution_dpi', models.PositiveIntegerField(default=300, help_text='Minimum resolution in DPI')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_option', to='products.product')),
            ],
        ),
    ]
