# Generated by Django 5.2.6 on 2025-09-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_designoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design_templates',
            field=models.JSONField(blank=True, default=list, help_text='Available templates'),
        ),
    ]
