# Generated by Django 5.2.6 on 2025-09-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_useraddress_cart_user_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='design_files',
            field=models.JSONField(default=list, help_text='Uploaded design file URLs'),
        ),
    ]
