# Generated by Django 5.2.6 on 2025-09-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_tool', '0007_safe_uuid_migration'),
        ('orders', '0004_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design_tool.userdesign'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design_tool.userdesign'),
        ),
    ]
