# Generated by Django 4.2.7 on 2025-08-30 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('product_types', models.JSONField(default=list, help_text='Which products can use this template')),
                ('template_data', models.JSONField(help_text='Canvas data, elements, etc.')),
                ('preview_image', models.ImageField(blank=True, upload_to='templates/previews/')),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='templates/thumbnails/')),
                ('width', models.IntegerField(help_text='Width in pixels or mm')),
                ('height', models.IntegerField(help_text='Height in pixels or mm')),
                ('dpi', models.IntegerField(default=300)),
                ('color_mode', models.CharField(choices=[('RGB', 'RGB'), ('CMYK', 'CMYK')], default='CMYK', max_length=4)),
                ('tags', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('design_data', models.JSONField(help_text='Canvas data')),
                ('preview_image', models.ImageField(blank=True, upload_to='user_designs/previews/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design_tool.designtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
    ]
