# Generated by Django 4.2.7 on 2025-08-30 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='SVG template file or JSON canvas data', null=True, upload_to='templates/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'json'])]),
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='final_height_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='final_width_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='is_ready_for_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='height',
            field=models.FloatField(help_text='Height in mm'),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_review', 'Pending Review')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='template_data',
            field=models.JSONField(blank=True, help_text='Parsed canvas data from SVG', null=True),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='width',
            field=models.FloatField(help_text='Width in mm'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='design_data',
            field=models.JSONField(help_text='Fabric.js canvas data'),
        ),
    ]
