# Generated by Django 4.2.7 on 2025-08-30 11:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_tool', '0002_designtemplate_template_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='design_assets/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='design_assets/thumbs/')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('icon', 'Icon'), ('logo', 'Logo'), ('texture', 'Texture')], default='image', max_length=20)),
                ('file_size', models.IntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('canvas_state', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DesignShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit'), ('admin', 'Admin Access')], default='view', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('api_source', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('thumbnail_url', models.URLField()),
                ('medium_url', models.URLField()),
                ('large_url', models.URLField()),
                ('photographer', models.CharField(blank=True, max_length=200)),
                ('photographer_url', models.URLField(blank=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='bleed_mm',
            field=models.FloatField(default=3.0, help_text='Bleed area in mm'),
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='min_font_size',
            field=models.FloatField(default=6.0, help_text='Minimum font size in pt'),
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='safe_area_mm',
            field=models.FloatField(default=5.0, help_text='Safe area margin in mm'),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='dpi',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='last_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='parent_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_tool.userdesign'),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='print_ready_pdf',
            field=models.FileField(blank=True, upload_to='user_designs/pdfs/'),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_review', 'Pending Review'), ('draft', 'Draft')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='template_data',
            field=models.JSONField(blank=True, help_text='Konva.js compatible canvas data', null=True),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='SVG template file or Konva JSON canvas data', null=True, upload_to='templates/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'json'])]),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='design_data',
            field=models.JSONField(help_text='Konva.js canvas data'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='designtemplate',
            index=models.Index(fields=['category', 'status'], name='design_tool_categor_f420f4_idx'),
        ),
        migrations.AddIndex(
            model_name='designtemplate',
            index=models.Index(fields=['is_featured', 'status'], name='design_tool_is_feat_97299b_idx'),
        ),
        migrations.AddIndex(
            model_name='userdesign',
            index=models.Index(fields=['user', 'is_favorite'], name='design_tool_user_id_d1088f_idx'),
        ),
        migrations.AddIndex(
            model_name='userdesign',
            index=models.Index(fields=['user', 'created_at'], name='design_tool_user_id_20272e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockimage',
            index=models.Index(fields=['api_source', 'created_at'], name='design_tool_api_sou_d6a729_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockimage',
            unique_together={('external_id', 'api_source')},
        ),
        migrations.AddField(
            model_name='designshare',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_tool.userdesign'),
        ),
        migrations.AddField(
            model_name='designshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designhistory',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='design_tool.userdesign'),
        ),
        migrations.AddField(
            model_name='designasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_designs', through='design_tool.DesignShare', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='designshare',
            unique_together={('design', 'user')},
        ),
    ]
