# Generated by Django 4.2.7 on 2025-08-30 11:45

from django.db import migrations


def clear_invalid_data(apps, schema_editor):
    """Clear any invalid UUID data that might exist"""
    try:
        # Clear any existing data with invalid UUIDs to start fresh
        DesignTemplate = apps.get_model('design_tool', 'DesignTemplate')
        UserDesign = apps.get_model('design_tool', 'UserDesign')
        
        # Delete all existing records to start fresh - this is safe for development
        DesignTemplate.objects.all().delete()
        UserDesign.objects.all().delete()
        
    except Exception:
        # If there are any issues, just continue
        pass


def reverse_clear_invalid_data(apps, schema_editor):
    """Reverse is not applicable"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('design_tool', '0003_designasset_designhistory_designshare_stockimage_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_invalid_data, reverse_clear_invalid_data),
    ]
