# Generated by Django 5.2.6 on 2025-09-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_tool', '0005_add_front_back_design_support'),
    ]

    operations = [
    ]
