# Generated by Django 5.2.6 on 2025-09-21 10:33

from django.db import migrations


def rename_field_if_exists(apps, schema_editor):
    """Safely rename field if it exists"""
    try:
        DesignAsset = apps.get_model('design_tool', 'DesignAsset')
        from django.db import connection
        cursor = connection.cursor()

        # Check if 'file' column exists and 'asset_file' doesn't
        cursor.execute("PRAGMA table_info(design_tool_designasset)")
        columns = [column[1] for column in cursor.fetchall()]

        if 'file' in columns and 'asset_file' not in columns:
            cursor.execute("ALTER TABLE design_tool_designasset RENAME COLUMN file TO asset_file")
            print("Renamed 'file' column to 'asset_file' in DesignAsset")

    except Exception as e:
        print(f"Column rename operation skipped: {e}")


def reverse_rename_field(apps, schema_editor):
    """Reverse the rename operation"""
    try:
        from django.db import connection
        cursor = connection.cursor()

        # Check if 'asset_file' column exists and 'file' doesn't
        cursor.execute("PRAGMA table_info(design_tool_designasset)")
        columns = [column[1] for column in cursor.fetchall()]

        if 'asset_file' in columns and 'file' not in columns:
            cursor.execute("ALTER TABLE design_tool_designasset RENAME COLUMN asset_file TO file")
            print("Renamed 'asset_file' column back to 'file' in DesignAsset")

    except Exception as e:
        print(f"Reverse column rename operation skipped: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('design_tool', '0007_safe_uuid_migration'),
    ]

    operations = [
        migrations.RunPython(rename_field_if_exists, reverse_rename_field),
    ]
